version: 2

workflows:
  version: 2
  License Finder Check:
    jobs:
       - dependency licenses check
       - devdependency licenses check


jobs:
  devdependency licenses check:
    docker:
      - image: licensefinder/license_finder
    steps:
      - checkout
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node modules
          command: npm ci
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Check dev-dependency licenses
          shell: /bin/bash --login -eo pipefail
          command: |
            license_finder --decisions-file=license_finder/doc/dev-decisions.yml
  dependency licenses check:
    docker:
      - image: licensefinder/license_finder
    steps:
      - checkout
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node modules
          command: npm ci
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Check dependency licenses
          shell: /bin/bash --login -eo pipefail
          command: |
            license_finder --decisions-file=license_finder/doc/decisions.yml